-- AlterEnum
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'JAZZCASH';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'EASYPAISA';

-- AlterTable
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN NOT NULL DEFAULT true;
