-- CreateEnum
CREATE TYPE "CaseType" AS ENUM ('CIVIL', 'CRIMINAL', 'FAMILY', 'CORPORATE', 'CONSTITUTIONAL', 'REVENUE', 'OTHER');

-- AlterTable
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "case_type" "CaseType" NOT NULL DEFAULT 'CIVIL',
ADD COLUMN IF NOT EXISTS "opposing_lawyer" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN NOT NULL DEFAULT true;
